language: node_js
node_js:
  - 8.9.3

branches:
  only:
  - master

#before_script:
# - chmod 600 ~/.ssh/id_rsa

env:
  global:
  - GH_REF: github.com/rickyscoder/Backend.git

before_install:
  - openssl aes-256-cbc -K $encrypted_f27c7aac39c5_key -iv $encrypted_f27c7aac39c5_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
# # 配置git 的个人信息
#   - git config --global user.name 'xxx'
#   - git config --global user.email xxx@xxx.com
# 配置 ssh
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config

install:
  - npm install pm2 -g
  - npm install

script: 
  - npm run start

after_success:
  - ssh -t root@47.104.215.172 -p 22 'cd /home/node-avntador/Backend && git pull && npm run start'
