apps:
  - script: app.js
    name: mybackend
    # instances: 4
    exec_mode: fork
  # 第二个实例
  # - script : worker.js
    watch: true
    # 通过 process.env.NODE_ENV 获取
    # pm2通过在配置文件中通过env_xx来声明不同环境的配置，
    # 然后在启动应用时，通过--env参数指定运行的环境
    # pm2 start app.js --env development
    env:
      NODE_ENV: dev
      # 自定义多个环境变量
      VARIABLE_ENV: development
    env_production:
      NODE_ENV: prod
    log_date_format  : YYYY-MM-DD HH:mm Z
    error_file : ./logs/error/child-err.log
    out_file   : ./logs/out/child-out.log
    # pid_file   : ./examples/child.pid
    min_uptime: 30000
    restart_delay: 1000
    #  200 seconds, defaults to 1000
    autorestart: true
    max_restarts: 10
    #  defaults to 15
    max_memory_restart: 1M
    #  1 megabytes, e.g.: 2G, 10M, 100K, 1024 the default unit is byte.